### ISSUE TITLE
 Hack And Chat April 2021

### ISSUE THREAD

**Issue by mre** [hello-rust/community#3]
Let's chat about Rust!
If you want to propose a talk, add a comment here. 😊

* Date: 12th of April
* Time: 8pm GMT+1 (Berlin,Paris...)
* Location: https://gather.town/app/0Ez2adaJDhN67Xzw/rust
* Language: English

**Comment by soruh** [comment]
I have been playing around with running Rust on x86_64 linux with neither std nor libc and could give a talk on that if there is interest.

Note that this project is **not** about actually running production code without a libc
but about learning how libc / std work under the hood. 

Since there is quite a lot to talk about I would probably prepare some slides to present the project in general and describe each of the components (basically the list below) and then explain the ones people are most interested in as much detail as desired (probably while showing/explaining the relevant code).

If there is already interest in specific topics I can of course prepare a bit more for them (write some slides and life demos, for example).

### Possible Topics (in order of ascending complexity):
- environment parsing:
making sense of the data given to you by the kernel (environment variables and arguments)
- syscalls:
interfacing directly with the linux kernel
- io:
writing to stderr and stdout, reading from stdin, reproducing a std experience 
- startfiles:
implementing the things we loose by linking with `-nostartfiles` in rust
(everything in between `_start` and `main`)
- sync:
locking primitives (a naïve spin Mutex and a more complex one using the `futex` syscall)
- allocation:
global allocations: `brk` and `mmap`, a primitive bump allocator and a more complex one (which actually frees memory)
- threading:
spawning threads, waiting for their completion and receiving their results
this topic has a lot of pitfalls and unsafties that I found very interesting to find out about (read: "struggle with random SegFaults")
and some very cool functionality supplied by the linux kernel


as a small teaser:

<details>
  <summary>this is the main function of my threading test</summary>
  
```rust
unsafe fn thread_test_main(_env: Environment) -> i8 {
    const N_LOOPS: usize = 2_000_000;
    const N_THREADS: usize = 16;

    println!("Hello, World!");

    info!("spawning...");

    // Safety: The Mutex is `Pin`ned by the `Arc::pin`.
    let data = Arc::pin(Mutex::new(0));

    let handles: Vec<_> = (0..N_THREADS)
        .into_iter()
        .map(|i| {
            let data = data.clone();

            thread::spawn(
                move || {
                    info!("child {:X?}...", i);

                    for _ in 0..N_LOOPS {
                        *data.lock() += 1;
                    }

                    info!("child {:X?} done", i);

                    42
                },
                1024 * 1024,
            )
            .expect("Failed to spawn thread")
        })
        .collect();

    for _ in 0..(N_THREADS * N_LOOPS) {
        *data.lock() -= 1;
    }

    info!("parent waiting...");

    for handle in handles {
        assert_eq!(handle.join().unwrap(), 42);
    }

    info!("parent done");

    assert_eq!(*data.lock(), 0);

    info!("sleeping...");

    syscalls::sleep(Duration::from_secs(1)).unwrap();

    info!("done");

    0
}
```
</details>

**Comment by mre** [comment]
Very nice @soruh. A talk would be very desirable. I'll make sure to announce your talk on twitter as the event comes closer. Probably a week before the meetup or so.
Could you provide an abstract for your talk here that I could use for Twitter?

Also, come to think of it, would you be interested in having the talk recorded? That's fully optional of course and I could understand if you didn't want that, but I thought I'd just ask because more people might be interested in that topic and your project in the future. We could talk about the details in private if you prefer that. (And for the rest, we'd announce the beginning and the end of the recording during the meetup. Only the slides and perhaps the speak will be recorded in this case.)

**Comment by mre** [comment]
Thanks everyone for participating. 🥳 Closing this.
@soruh, feel free to attach the slides and potential video link here for future reference.

**Comment by mre** [comment]
In the meantime, here is @soruh's project: https://github.com/soruh/barebones-x86-linux

**Comment by soruh** [comment]
The sources for the slides are in the root of the project but I will post a link to the rendered version later.
I'll also post a link to the video once I find the time to edit and upload it.

Thanks again for organizing this!
